#!/usr/bin/env python3
# Copyright (c) 2025 Basalte bv
#
# SPDX-License-Identifier: Apache-2.0

"""
A script to plot data in a sunburst chart generated by size_report.
When you call the ram_report or rom_report targets you end up
with a json file in the build directory that can be used as input
for this script.

Example:
   ./scripts/footprint/plot.py build/ram.json

Requires plotly to be installed, for example with pip:
   pip install plotly
"""

import argparse
import json

try:
    import plotly.graph_objects as go
except ImportError:
    print("Missing dependency: You need to install plotly (see scripts/requirements-extra.txt).")
    raise


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        allow_abbrev=False,
    )

    parser.add_argument('input', help='Input json file')
    parser.add_argument('--html', help='Output html file')
    parser.add_argument(
        '--depth',
        help='Maximum render depth, pass -1 to render all levels. Defaults to 4',
        type=int,
        default=4,
    )

    return parser.parse_args()


def generate_figure(data, depth=4):
    totalsize = data.get('total_size', 0)
    ids = []
    labels = []
    parents = []
    values = []
    hovertext = []
    # Zgmicro Start
    # Track which index each id maps to, plus parent->children indices.
    children_idx = {}
    # Zgmicro End

    def iter_node(node: dict, parent=''):
        identifier = node.get('identifier')
        if identifier is None:
            return

        if identifier in ids:
            # Identifiers aren't unique, add a suffix to make them unique
            idx = 0
            while f'{identifier}_{idx}' in ids:
                idx += 1
            identifier = f'{identifier}_{idx}'

        # Zgmicro Start
        idx = len(ids)
        # Zgmicro End
        ids.append(identifier)
        labels.append(node.get('name', ''))
        parents.append(parent)
        values.append(node.get('size', 0))
        # Zgmicro Start
        children_idx.setdefault(parent, []).append(idx)
        # Zgmicro End

        details = []
        if totalsize > 0:
            details.append(f'percentage: {node.get("size") / totalsize:.2%}')
        if 'address' in node:
            details.append(f'address: 0x{node.get("address"):08x}')
        if 'section' in node:
            details.append(f'section: {node.get("section")}')

        hovertext.append("<br>".join(details))

        for child in node.get('children', ()):
            iter_node(child, identifier)

    iter_node(data.get('symbols', {}))

    # Zgmicro Start
    # Normalize values top-down so sum(children) == parent for every branch.
    # The size_report JSON occasionally contains "organizational" parent nodes
    # with size 0 whose children have non-zero sizes (e.g. the synthetic "/"
    # filesystem root that duplicates the "(hidden)" subtree). Plotly.js v3
    # strictly rejects branchvalues='total' mismatches and silently renders an
    # empty chart, so we enforce consistency here while preserving the reported
    # parent sizes (which match the textual table).
    def normalize(node_idx):
        node_id = ids[node_idx]
        parent_val = values[node_idx]
        kids = list(children_idx.get(node_id, ()))
        if not kids:
            return
        child_sum = sum(values[ci] for ci in kids)
        if parent_val == 0:
            # Purely organizational node: zero the whole subtree so it doesn't
            # double-count against sibling branches.
            for ci in kids:
                values[ci] = 0
                normalize(ci)
            return
        if child_sum > parent_val and child_sum > 0:
            # Children overshoot parent; scale them proportionally.
            for ci in kids:
                values[ci] = values[ci] * parent_val // child_sum
        elif child_sum < parent_val:
            # Missing contribution from the parent itself; add a "(self)" leaf.
            remainder = parent_val - child_sum
            ids.append(f'{node_id}__self')
            labels.append('(self)')
            parents.append(node_id)
            values.append(remainder)
            hovertext.append('')
            children_idx.setdefault(node_id, []).append(len(ids) - 1)
        for ci in kids:
            normalize(ci)

    for root_idx in children_idx.get('', ()):
        normalize(root_idx)
    # Zgmicro End

    fig = go.Figure(
        go.Sunburst(
            ids=ids,
            labels=labels,
            parents=parents,
            values=values,
            hovertext=hovertext,
            branchvalues='total',
            maxdepth=depth,
        ),
        skip_invalid=True,
    )
    fig.update_layout(margin={'t': 0, 'l': 0, 'r': 0, 'b': 0})
    fig.update_traces(textfont=dict(size=24))

    return fig


def main():
    args = parse_args()

    with open(args.input) as f:
        data = json.load(f)

    fig = generate_figure(data, args.depth)

    if args.html:
        fig.write_html(args.html, auto_open=False)
        return

    print("Opening the default browser to render the generated plot.")
    fig.show(renderer="browser")


if __name__ == "__main__":
    main()
